name: CI

on:
#  pull_request:
#  push:
#    branches:
#      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - run: cargo check
      
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        features:
          - "log,json"
          
    runs-on: ${{ matrix.os }}
    
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: feignhttp=debug

    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Run tests
        run: cargo test --features ${{ matrix.features }}
